FROM node:20-slim

# Set working directory
WORKDIR /app

COPY .sequelizerc .sequelizerc

# Install node dependencies
COPY package*.json ./
COPY src ./src
COPY public ./public
COPY server ./server
COPY tsconfig.json ./
COPY server/tsconfig.json ./server/
# COPY server/start.sh ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Build TypeScript server
ENV NODE_OPTIONS="--max-old-space-size=8192"
RUN npm run build:server

# Expose backend port
EXPOSE ${BACKEND_PORT:-8080}

# Run migrations & start backend using plain node
CMD ["npm", "run", "server"]
# CMD ["sh", "-c", "npm run migrate && npm run server"]